[build]
command = "hatch build"
path = "dist/"

[version]
tag_format = "v{version}"
version_variable = [
    "martor/__init__.py:__version__",
    "pyproject.toml:project.version",
]

[upload_to_release]
enabled = true
build_artifacts = true

[upload_to_pypi]
enabled = false
