# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import draceditor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', draceditor.models.DraceditorField()),
            ],
        ),
    ]
