BBBB BBBBBBBBBBBXXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX
XXXXXX
  XXXXXXXBBBBB BBBBBBBBBBBBB XX XXXXXXXXXXXXXX

  XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XX
  XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XX
  XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XX
  XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XX
  XXXXXXX
    XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX
  XXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX
XXXXXX
  XXXXXXXX
    XXXX XXXXXXXXX XXXXX XXXXXXXX XXXXXX
      XXXX XXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX
        XXXX
        XXXX XXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXX
          XX XXXXXXXXXXXXXXX XXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXX XXXXXXX
              XX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXX

  XXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXX XXXXXXXXX
      BBBBB BBBBBBBBBBBBBBB
    XXXXXX
  XXXXXX

  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX
XXXXXXX
